platform :ios, '9.0'
target 'Perinatal' do
   pod "ReactiveCocoa", '~> 2.5'# RAC,一个支持响应式编程的库.
   pod 'IQKeyboardManager'
   pod 'AFNetworking', '~> 3.0'
   pod 'Masonry'
   pod 'MJRefresh'
   pod 'MBProgressHUD', '~> 1.0.0'
   # 集成微信(精简版0.2M)
   pod 'UMengUShare/Social/ReducedWeChat'
   # 集成QQ(精简版0.5M)
   pod 'UMengUShare/Social/ReducedQQ'
   pod 'BAPickView'
end
